#./.github/workflows/build.yaml
name: "Build & Tests"
on:
  push:
    branches:
      - main # ou o nome do branch que vocês estão utilizando.
jobs:
  build:
    runs-on: ubuntu-latest
      env:
        DB_USER: root
        DB_PASSWORD: root
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Check runtime version
        run: php -v && composer --version
      - name: Install dependencies
        run: composer install -o
      - name: Start Mysql
        run: sudo systemctl start mysql
      - name: Create database
        run: bin/console doctrine:database:create
      - name: Create database schema
        run: bin/console doctrine:schema:create
      - name: Run functional tests
        run: bin/phpunit